[tool]
[tool.poetry]
authors = ["Dewstend"]
name = "fcc-sea-level-predictor"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = "^3.10"
scipy = "*"
matplotlib = "^3.8.3"
numpy = "^1.26.4"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.3"

